file<-read.csv("household_power_consumption.txt",header=T,sep=";")
file$Date <- as.Date(file$Date, format="%d/%m/%Y")
filefilter<-sqldf("select * from file where Date between '1/2/2007' and '2/2/2007' order by Date")
finaltime<-strptime(paste(filefilter$Date, filefilter$Time,sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
filefilter$Global_active_power<-as.numeric(filefilter$Global_active_power)
filefilter$Sub_metering_1 <- as.numeric(filefilter$Sub_metering_1)
filefilter$Sub_metering_2 <- as.numeric(filefilter$Sub_metering_2)
filefilter$Sub_metering_3 <- as.numeric(filefilter$Sub_metering_3)
plot(filefilter$finaltime,filefilter$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(filefilter$finaltime,filefilter$Sub_metering_2,col="red")
lines(filefilter$finaltime,filefilter$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.off()
